version: '3.3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    ports:
      - "8081:80"
    networks:
      - cornerstone-network
    environment:
      PMA_HOST: mysql
      PMA_HOSTS: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    command: --lower_case_table_names=1
    networks:
      - cornerstone-network
    environment:
      MYSQL_DATABASE: cornerstone
      MYSQL_USER: admin
      MYSQL_PASSWORD: mixthsNyf7OQ7rw2tH6k
      MYSQL_ROOT_PASSWORD: my@secret-root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  cornerstone-network:
    driver: bridge
volumes:
  dbdata: